runtime: python39  # replace with your Python version
entrypoint: gunicorn -b :$PORT app:app  # replace main:app with your application's entry point

instance_class: F2

automatic_scaling:
  target_cpu_utilization: .65
  min_instances: 1
  max_instances: 15
  min_pending_latency: automatic
  max_pending_latency: automatic
